(() => {
  const C=window.NEON_CONFIG||{}, D=window.NEON_DATA;
  const root=document.getElementById('adminApp'), toast=document.getElementById('toast');
  const ready=C.supabaseUrl&&C.supabaseAnonKey&&!C.supabaseUrl.includes('YOUR_');
  const sb=ready&&window.supabase?window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey):null;
  let user=null,profile=null,tab='dashboard',cache={courses:[],lessons:[],profiles:[],enrollments:[],orders:[],announcements:[],coupons:[],settings:[]};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=v=>new Intl.NumberFormat('en-GB',{style:'currency',currency:C.currency||'GBP'}).format(Number(v||0));
  const show=(m,t='success')=>{toast.textContent=m;toast.className=`toast ${t}`;setTimeout(()=>toast.classList.add('hidden'),3200)};

  async function init(){
    if(!sb){root.innerHTML=`<div class="admin-login"><h1>Control Room</h1><p>Supabase is not configured. Add the project URL and publishable key to <code>config.js</code>.</p></div>`;return;}
    const {data:{session}}=await sb.auth.getSession();user=session?.user||null;
    sb.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;await boot();});
    await boot();
  }
  async function boot(){
    if(!user){renderLogin();return;}
    const {data,error}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();
    if(error){renderError(error.message);return;} profile=data;
    if(!profile?.is_admin){root.innerHTML=`<div class="admin-login"><span class="eyebrow">Access denied</span><h1>This account is not an admin.</h1><p class="muted">Signed in as ${esc(user.email||'')}. Make this account an admin in Supabase using the SQL instruction in README.md.</p><button class="btn btn-secondary" id="adminLogout">Log out</button></div>`;$('#adminLogout').onclick=()=>sb.auth.signOut();return;}
    await loadAll();renderShell();
  }
  function renderLogin(){
    root.innerHTML=`<div class="admin-login"><span class="eyebrow">NEON owner tools</span><h1>Control Room</h1><p class="muted">Use your admin account. Learners cannot access this area.</p><div class="field"><label>Email</label><input id="email" type="email"></div><div class="field" style="margin-top:12px"><label>Password</label><input id="password" type="password"></div><button class="btn btn-primary btn-block" style="margin-top:16px" id="login">Log in</button><p class="muted" style="font-size:.76rem;margin-top:14px">Admin access is enforced by Supabase RLS, not just by hiding buttons in the website.</p></div>`;
    $('#login').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)show(error.message,'error');};
  }
  function renderError(msg){root.innerHTML=`<div class="admin-login"><h1>Control Room error</h1><p>${esc(msg)}</p></div>`;}

  async function loadAll(){
    const calls=await Promise.all([
      sb.from('courses').select('*').order('sort_order'),
      sb.from('lessons').select('*').order('course_slug').order('position'),
      sb.from('profiles').select('*').order('created_at',{ascending:false}),
      sb.from('enrollments').select('*').order('created_at',{ascending:false}),
      sb.from('orders').select('*').order('created_at',{ascending:false}),
      sb.from('announcements').select('*').order('created_at',{ascending:false}),
      sb.from('coupons').select('*').order('created_at',{ascending:false}),
      sb.from('site_settings').select('*').order('key')
    ]);
    ['courses','lessons','profiles','enrollments','orders','announcements','coupons','settings'].forEach((k,i)=>{if(!calls[i].error)cache[k]=calls[i].data||[];});
  }

  function renderShell(){
    root.innerHTML=`<div class="admin-layout"><aside class="admin-nav"><div class="admin-user"><strong>${esc(profile.display_name||'Owner')}</strong><small style="display:block;color:#8d9a91">${esc(user.email)}</small></div>${navBtn('dashboard','Overview')}${navBtn('courses','Courses & pricing')}${navBtn('lessons','Lessons')}${navBtn('learners','Learners & access')}${navBtn('orders','Orders')}${navBtn('announcements','Announcements')}${navBtn('coupons','Coupons')}${navBtn('settings','Site settings')}<button id="logout">Log out</button></aside><section class="admin-main" id="adminMain"></section></div>`;
    $$('.admin-nav [data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderShell();});$('#logout').onclick=()=>sb.auth.signOut();renderTab();
  }
  function navBtn(id,label){return `<button class="${tab===id?'active':''}" data-tab="${id}">${label}</button>`;}
  function renderTab(){({dashboard:renderDashboard,courses:renderCourses,lessons:renderLessons,learners:renderLearners,orders:renderOrders,announcements:renderAnnouncements,coupons:renderCoupons,settings:renderSettings}[tab]||renderDashboard)();}
  function main(){return $('#adminMain');}

  function renderDashboard(){
    const revenue=cache.orders.filter(o=>o.status==='paid').reduce((s,o)=>s+Number(o.amount||0),0), active=cache.enrollments.filter(e=>!e.expires_at||new Date(e.expires_at)>new Date()).length;
    main().innerHTML=`<div class="admin-title-row"><div><span class="eyebrow">Live overview</span><h1>Control Room</h1></div><button class="btn btn-secondary" id="refresh">Refresh data</button></div><div class="admin-grid"><div class="admin-card"><strong>${cache.profiles.length}</strong><span>Learner profiles</span></div><div class="admin-card"><strong>${active}</strong><span>Active enrolments</span></div><div class="admin-card"><strong>${cache.orders.filter(o=>o.status==='paid').length}</strong><span>Paid orders</span></div><div class="admin-card"><strong>${money(revenue)}</strong><span>Recorded revenue</span></div></div><div class="dashboard-grid" style="margin-top:18px"><div class="admin-form"><h2>Quick actions</h2><div class="admin-actions"><button class="btn btn-green" data-jump="learners">Grant course access</button><button class="btn btn-secondary" data-jump="courses">Change prices</button><button class="btn btn-secondary" data-jump="lessons">Add a lesson</button><button class="btn btn-secondary" data-jump="announcements">Post announcement</button></div></div><aside class="admin-form"><h2>System</h2><p><span class="tag green">Supabase connected</span></p><p class="muted">RLS protects admin tables. Never put your service role key in GitHub.</p></aside></div><div class="admin-form"><h2>Recent orders</h2>${ordersTable(cache.orders.slice(0,6))}</div>`;
    $('#refresh').onclick=async()=>{await loadAll();renderDashboard();show('Data refreshed');};$$('[data-jump]').forEach(b=>b.onclick=()=>{tab=b.dataset.jump;renderShell();});
  }

  function renderCourses(){
    main().innerHTML=`<div class="admin-title-row"><div><span class="eyebrow">Catalogue</span><h1>Courses & pricing</h1></div><span class="tag">Changes appear on the learner site</span></div><div class="table-wrap"><table><thead><tr><th>Course</th><th>Focus</th><th>Price</th><th>Access</th><th>Payment link</th><th>Status</th><th></th></tr></thead><tbody>${cache.courses.map(c=>`<tr><td><b>${esc(c.name)}</b><br><small>${esc(c.slug)}</small></td><td>${esc(c.focus||'')}</td><td>${money(c.price)}</td><td>${c.days} days</td><td>${c.payment_url?'<span class="tag green">Connected</span>':'<span class="tag">Not set</span>'}</td><td>${c.active?'<span class="tag green">Live</span>':'<span class="tag red">Hidden</span>'}</td><td><button class="btn btn-secondary btn-sm" data-edit-course="${c.slug}">Edit</button></td></tr>`).join('')}</tbody></table></div>`;
    $$('[data-edit-course]').forEach(b=>b.onclick=()=>editCourse(b.dataset.editCourse));
  }
  function editCourse(slug){const c=cache.courses.find(x=>x.slug===slug);main().innerHTML=`<div class="admin-title-row"><h1>Edit ${esc(c.name)}</h1><button class="btn btn-secondary" data-back>← Back</button></div><div class="admin-form"><div class="form-grid"><div class="field"><label>Name</label><input id="cName" value="${esc(c.name)}"></div><div class="field"><label>Focus</label><input id="cFocus" value="${esc(c.focus||'')}"></div><div class="field"><label>Price (£)</label><input id="cPrice" type="number" step="0.01" value="${Number(c.price)}"></div><div class="field"><label>Access days</label><input id="cDays" type="number" value="${Number(c.days)}"></div><div class="field full"><label>Description</label><textarea id="cDetail" rows="4">${esc(c.detail||'')}</textarea></div><div class="field full"><label>Payment URL</label><input id="cPayment" type="url" value="${esc(c.payment_url||'')}" placeholder="Add a payment link later"></div><div class="field"><label>Sort order</label><input id="cSort" type="number" value="${Number(c.sort_order||0)}"></div><div class="field"><label>Live</label><select id="cActive"><option value="true" ${c.active?'selected':''}>Yes</option><option value="false" ${!c.active?'selected':''}>No</option></select></div></div><button class="btn btn-green" id="saveCourse" style="margin-top:14px">Save changes</button></div>`; $('[data-back]').onclick=()=>renderCourses();$('#saveCourse').onclick=async()=>{const payload={name:$('#cName').value,focus:$('#cFocus').value,price:Number($('#cPrice').value),days:Number($('#cDays').value),detail:$('#cDetail').value,payment_url:$('#cPayment').value||null,sort_order:Number($('#cSort').value),active:$('#cActive').value==='true',updated_at:new Date().toISOString()};const {error}=await sb.from('courses').update(payload).eq('slug',slug);if(error)return show(error.message,'error');await loadAll();show('Course updated');renderCourses();};}

  function renderLessons(){
    main().innerHTML=`<div class="admin-title-row"><div><span class="eyebrow">Content</span><h1>Lessons</h1></div><button class="btn btn-green" id="newLesson">+ New lesson</button></div><div class="admin-form"><div class="field"><label>Filter course</label><select id="lessonFilter"><option value="">All courses</option>${cache.courses.map(c=>`<option value="${c.slug}">${esc(c.name)}</option>`).join('')}</select></div></div><div id="lessonTable">${lessonTable(cache.lessons)}</div>`;
    $('#newLesson').onclick=()=>editLesson(null);$('#lessonFilter').onchange=e=>$('#lessonTable').innerHTML=lessonTable(cache.lessons.filter(l=>!e.target.value||l.course_slug===e.target.value));bindLessonButtons();
  }
  function lessonTable(list){return `<div class="table-wrap"><table><thead><tr><th>Course</th><th>Module</th><th>Lesson</th><th>Key</th><th>Order</th><th>Status</th><th></th></tr></thead><tbody>${list.map(l=>`<tr><td>${esc(l.course_slug)}</td><td>${esc(l.module_title||'')}</td><td><b>${esc(l.title)}</b><br><small>${esc(l.summary||'')}</small></td><td>${esc(l.lesson_key)}</td><td>${l.position}</td><td>${l.published?'<span class="tag green">Published</span>':'<span class="tag">Draft</span>'}</td><td><button class="btn btn-secondary btn-sm" data-edit-lesson="${l.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="7">No database lesson overrides yet. Static built-in lessons still work on the site.</td></tr>'}</tbody></table></div>`;}
  function bindLessonButtons(){$$('[data-edit-lesson]').forEach(b=>b.onclick=()=>editLesson(b.dataset.editLesson));}
  function editLesson(id){const l=id?cache.lessons.find(x=>x.id===id):{course_slug:'pro',lesson_key:'',module_title:'New module',title:'',summary:'',body:'',type:'lesson',position:100,published:true};main().innerHTML=`<div class="admin-title-row"><h1>${id?'Edit':'New'} lesson</h1><button class="btn btn-secondary" data-back>← Back</button></div><div class="admin-form"><div class="form-grid"><div class="field"><label>Course</label><select id="lCourse">${cache.courses.map(c=>`<option value="${c.slug}" ${c.slug===l.course_slug?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Lesson key</label><input id="lKey" value="${esc(l.lesson_key||'')}" placeholder="e.g. p2q5-extra"></div><div class="field"><label>Module</label><input id="lModule" value="${esc(l.module_title||'')}"></div><div class="field"><label>Type</label><select id="lType">${['lesson','interactive','checklist','quiz'].map(t=>`<option ${t===l.type?'selected':''}>${t}</option>`).join('')}</select></div><div class="field full"><label>Title</label><input id="lTitle" value="${esc(l.title||'')}"></div><div class="field full"><label>Summary</label><input id="lSummary" value="${esc(l.summary||'')}"></div><div class="field full"><label>Body — blank line between paragraphs</label><textarea id="lBody" rows="14">${esc(l.body||'')}</textarea></div><div class="field"><label>Position</label><input id="lPos" type="number" value="${Number(l.position||100)}"></div><div class="field"><label>Published</label><select id="lPublished"><option value="true" ${l.published?'selected':''}>Yes</option><option value="false" ${!l.published?'selected':''}>No</option></select></div></div><div class="admin-actions" style="margin-top:14px"><button class="btn btn-green" id="saveLesson">Save</button>${id?'<button class="btn btn-danger" id="deleteLesson">Delete</button>':''}</div></div>`;$('[data-back]').onclick=()=>renderLessons();$('#saveLesson').onclick=async()=>{const payload={course_slug:$('#lCourse').value,lesson_key:$('#lKey').value.trim(),module_title:$('#lModule').value.trim(),type:$('#lType').value,title:$('#lTitle').value.trim(),summary:$('#lSummary').value.trim(),body:$('#lBody').value,position:Number($('#lPos').value),published:$('#lPublished').value==='true',updated_at:new Date().toISOString()};if(!payload.lesson_key||!payload.title)return show('Lesson key and title are required','error');const q=id?sb.from('lessons').update(payload).eq('id',id):sb.from('lessons').insert(payload);const {error}=await q;if(error)return show(error.message,'error');await loadAll();show('Lesson saved');renderLessons();};$('#deleteLesson')?.addEventListener('click',async()=>{if(!confirm('Delete this database lesson?'))return;const {error}=await sb.from('lessons').delete().eq('id',id);if(error)return show(error.message,'error');await loadAll();renderLessons();show('Lesson deleted');});}

  function renderLearners(){
    main().innerHTML=`<div class="admin-title-row"><div><span class="eyebrow">Accounts</span><h1>Learners & access</h1></div></div><div class="admin-form"><h2>Grant course access</h2><div class="form-grid"><div class="field"><label>Learner email</label><input id="grantEmail" type="email" placeholder="student@example.com"></div><div class="field"><label>Course</label><select id="grantCourse">${cache.courses.map(c=>`<option value="${c.slug}" data-days="${c.days}">${esc(c.name)} — ${c.days} days</option>`).join('')}</select></div><div class="field"><label>Days</label><input id="grantDays" type="number" value="${cache.courses[0]?.days||14}"></div><div class="field" style="align-self:end"><button class="btn btn-green" id="grant">Grant access</button></div></div></div><div class="table-wrap"><table><thead><tr><th>Learner</th><th>Year</th><th>Target</th><th>Role</th><th>Joined</th><th>Active courses</th></tr></thead><tbody>${cache.profiles.map(p=>{const es=cache.enrollments.filter(e=>e.user_id===p.id&&(!e.expires_at||new Date(e.expires_at)>new Date()));return `<tr><td><b>${esc(p.display_name||'Learner')}</b><br><small>${esc(p.email||'')}</small></td><td>${esc(p.year_group||'—')}</td><td>${esc(p.target_grade||'—')}</td><td>${p.is_admin?'<span class="tag purple">Admin</span>':'Learner'}</td><td>${new Date(p.created_at).toLocaleDateString('en-GB')}</td><td>${es.length?es.map(e=>`<span class="tag green">${esc(e.course_slug)}</span>`).join(' '):'—'}</td></tr>`}).join('')}</tbody></table></div>`;
    $('#grantCourse').onchange=e=>$('#grantDays').value=e.target.selectedOptions[0].dataset.days;$('#grant').onclick=async()=>{const {error}=await sb.rpc('grant_access_by_email',{p_email:$('#grantEmail').value.trim(),p_course_slug:$('#grantCourse').value,p_days:Number($('#grantDays').value)});if(error)return show(error.message,'error');await loadAll();show('Course access granted');renderLearners();};
  }

  function ordersTable(list){return `<div class="table-wrap"><table><thead><tr><th>Date</th><th>Email</th><th>Course</th><th>Amount</th><th>Status</th><th>Reference</th></tr></thead><tbody>${list.map(o=>`<tr><td>${new Date(o.created_at).toLocaleDateString('en-GB')}</td><td>${esc(o.email||'')}</td><td>${esc(o.course_slug||'')}</td><td>${money(o.amount)}</td><td><span class="tag ${o.status==='paid'?'green':o.status==='failed'?'red':''}">${esc(o.status||'pending')}</span></td><td>${esc(o.payment_ref||'—')}</td></tr>`).join('')||'<tr><td colspan="6">No orders yet.</td></tr>'}</tbody></table></div>`;}
  function renderOrders(){main().innerHTML=`<div class="admin-title-row"><div><span class="eyebrow">Commerce</span><h1>Orders</h1></div><button class="btn btn-secondary" id="refreshOrders">Refresh</button></div><div class="admin-grid" style="margin-bottom:18px"><div class="admin-card"><strong>${cache.orders.length}</strong><span>All orders</span></div><div class="admin-card"><strong>${cache.orders.filter(o=>o.status==='paid').length}</strong><span>Paid</span></div><div class="admin-card"><strong>${money(cache.orders.filter(o=>o.status==='paid').reduce((s,o)=>s+Number(o.amount||0),0))}</strong><span>Paid revenue</span></div><div class="admin-card"><strong>${cache.orders.filter(o=>o.status==='pending').length}</strong><span>Pending</span></div></div>${ordersTable(cache.orders)}<div class="callout"><strong>Important:</strong> do not mark payments as paid from browser code. A real payment provider should confirm payment server-side, then create the order/enrolment securely.</div>`;$('#refreshOrders').onclick=async()=>{await loadAll();renderOrders();};}

  function renderAnnouncements(){main().innerHTML=`<div class="admin-title-row"><div><span class="eyebrow">Site message</span><h1>Announcements</h1></div><button class="btn btn-green" id="newAnnouncement">+ New</button></div><div class="table-wrap"><table><thead><tr><th>Title</th><th>Message</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>${cache.announcements.map(a=>`<tr><td><b>${esc(a.title)}</b></td><td>${esc(a.body)}</td><td>${a.active?'<span class="tag green">Live</span>':'Hidden'}</td><td>${new Date(a.created_at).toLocaleDateString('en-GB')}</td><td><button class="btn btn-secondary btn-sm" data-edit-ann="${a.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="5">No announcements.</td></tr>'}</tbody></table></div>`;$('#newAnnouncement').onclick=()=>editAnnouncement();$$('[data-edit-ann]').forEach(b=>b.onclick=()=>editAnnouncement(b.dataset.editAnn));}
  function editAnnouncement(id){const a=id?cache.announcements.find(x=>x.id===id):{title:'',body:'',active:true};main().innerHTML=`<div class="admin-title-row"><h1>${id?'Edit':'New'} announcement</h1><button class="btn btn-secondary" data-back>← Back</button></div><div class="admin-form"><div class="field"><label>Title</label><input id="aTitle" value="${esc(a.title)}"></div><div class="field" style="margin-top:12px"><label>Message</label><textarea id="aBody" rows="5">${esc(a.body)}</textarea></div><div class="field" style="margin-top:12px"><label>Status</label><select id="aActive"><option value="true" ${a.active?'selected':''}>Live</option><option value="false" ${!a.active?'selected':''}>Hidden</option></select></div><div class="admin-actions" style="margin-top:14px"><button class="btn btn-green" id="saveAnn">Save</button>${id?'<button class="btn btn-danger" id="delAnn">Delete</button>':''}</div></div>`;$('[data-back]').onclick=renderAnnouncements;$('#saveAnn').onclick=async()=>{const payload={title:$('#aTitle').value.trim(),body:$('#aBody').value.trim(),active:$('#aActive').value==='true'};const q=id?sb.from('announcements').update(payload).eq('id',id):sb.from('announcements').insert(payload);const {error}=await q;if(error)return show(error.message,'error');await loadAll();show('Announcement saved');renderAnnouncements();};$('#delAnn')?.addEventListener('click',async()=>{await sb.from('announcements').delete().eq('id',id);await loadAll();renderAnnouncements();});}

  function renderCoupons(){main().innerHTML=`<div class="admin-title-row"><div><span class="eyebrow">Promotions</span><h1>Coupons</h1></div><button class="btn btn-green" id="newCoupon">+ New coupon</button></div><div class="table-wrap"><table><thead><tr><th>Code</th><th>Discount</th><th>Course</th><th>Uses</th><th>Expires</th><th>Status</th></tr></thead><tbody>${cache.coupons.map(c=>`<tr><td><b>${esc(c.code)}</b></td><td>${c.discount_percent}%</td><td>${esc(c.course_slug||'All')}</td><td>${c.used_count||0}${c.max_uses?` / ${c.max_uses}`:''}</td><td>${c.expires_at?new Date(c.expires_at).toLocaleDateString('en-GB'):'—'}</td><td>${c.active?'<span class="tag green">Active</span>':'Inactive'}</td></tr>`).join('')||'<tr><td colspan="6">No coupons yet.</td></tr>'}</tbody></table></div><div class="callout">Coupons are stored and manageable here. Your future secure checkout webhook should validate them server-side before applying a discount.</div>`;$('#newCoupon').onclick=()=>{main().innerHTML=`<div class="admin-title-row"><h1>New coupon</h1><button class="btn btn-secondary" data-back>← Back</button></div><div class="admin-form"><div class="form-grid"><div class="field"><label>Code</label><input id="cpCode" placeholder="NEON10"></div><div class="field"><label>Discount %</label><input id="cpDiscount" type="number" min="1" max="100" value="10"></div><div class="field"><label>Course</label><select id="cpCourse"><option value="">All courses</option>${cache.courses.map(c=>`<option value="${c.slug}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Maximum uses</label><input id="cpMax" type="number" placeholder="Leave blank for no limit"></div><div class="field"><label>Expiry</label><input id="cpExp" type="datetime-local"></div></div><button class="btn btn-green" id="saveCoupon" style="margin-top:14px">Create coupon</button></div>`;$('[data-back]').onclick=renderCoupons;$('#saveCoupon').onclick=async()=>{const payload={code:$('#cpCode').value.trim().toUpperCase(),discount_percent:Number($('#cpDiscount').value),course_slug:$('#cpCourse').value||null,max_uses:$('#cpMax').value?Number($('#cpMax').value):null,expires_at:$('#cpExp').value?new Date($('#cpExp').value).toISOString():null,active:true};const {error}=await sb.from('coupons').insert(payload);if(error)return show(error.message,'error');await loadAll();show('Coupon created');renderCoupons();};};}

  function renderSettings(){
    const byKey=k=>cache.settings.find(x=>x.key===k)?.value;
    main().innerHTML=`<div class="admin-title-row"><div><span class="eyebrow">Configuration</span><h1>Site settings</h1></div></div><div class="admin-form"><div class="form-grid"><div class="field full"><label>Homepage notice</label><input id="sNotice" value="${esc(byKey('homepage_notice')||'')}"></div><div class="field"><label>New signups</label><select id="sSignups"><option value="true" ${byKey('signups_enabled')!==false?'selected':''}>Enabled</option><option value="false" ${byKey('signups_enabled')===false?'selected':''}>Disabled</option></select></div><div class="field"><label>Maintenance mode</label><select id="sMaintenance"><option value="false" ${!byKey('maintenance_mode')?'selected':''}>Off</option><option value="true" ${byKey('maintenance_mode')?'selected':''}>On</option></select></div></div><button class="btn btn-green" id="saveSettings" style="margin-top:14px">Save settings</button></div><div class="admin-form"><h2>Payment setup status</h2><p>Course payment URLs are configured individually under <b>Courses & pricing</b>.</p><p class="muted">For automatic enrolment after payment, use a payment provider webhook in a trusted server environment such as a Supabase Edge Function. Do not put payment secrets in GitHub Pages.</p></div><div class="admin-form"><h2>Your public configuration</h2><div class="code-box">Supabase URL: ${esc(C.supabaseUrl||'')}
Publishable key: configured
Support email: ${esc(C.supportEmail||'')}
Demo mode: ${String(!!C.demoMode)}</div></div>`;
    $('#saveSettings').onclick=async()=>{const rows=[{key:'homepage_notice',value:$('#sNotice').value,is_public:true},{key:'signups_enabled',value:$('#sSignups').value==='true',is_public:true},{key:'maintenance_mode',value:$('#sMaintenance').value==='true',is_public:true}];for(const r of rows){const {error}=await sb.from('site_settings').upsert(r,{onConflict:'key'});if(error)return show(error.message,'error');}await loadAll();show('Settings saved');};
  }

  init();
})();
